In [3]:
import numpy as np
import pandas as pd

downloading the data

In [4]:
concrete_data=pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

Check the dataset for any missing values

In [5]:
concrete_data.describe()
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

Our dataset is clean, so no need to work on it

split the data into predictors and targets

In [6]:
concrete_data_columns=concrete_data.columns
predictors=concrete_data[concrete_data_columns[concrete_data_columns!='Strength']]# all the columns except strength
target=concrete_data['Strength']

In [7]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [8]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

Normalize the dataset

In [9]:
predictors=(predictors-predictors.mean())/predictors.std()
predictors

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069
...,...,...,...,...,...,...,...,...
1025,-0.045623,0.487998,0.564271,-0.092126,0.451190,-1.322363,-0.065861,-0.279597
1026,0.392628,-0.856472,0.959602,0.675872,0.702285,-1.993711,0.496651,-0.279597
1027,-1.269472,0.759210,0.850222,0.521336,-0.017520,-1.035561,0.080068,-0.279597
1028,-1.168042,1.307430,-0.846733,-0.279443,0.852942,0.214537,0.191074,-0.279597
1029,-0.193939,0.308349,0.376762,0.891286,0.400971,-1.394385,-0.150675,-0.279597

let's save the number of predictors to n_cols, since we will need them later

In [10]:
predictors_norm=predictors
n_col=predictors_norm.shape[1]

In [11]:
print(n_col)

8

In [16]:
import keras

In [17]:
from keras.models import Sequential
from keras.layers import Dense

In [14]:
import sys
print(sys.maxsize > 2**32)

True

In [18]:
# create model
model=Sequential()
model.add(Dense(50,activation='relu',input_shape=(n_col,)))
model.add(Dense(50,activation='relu'))
model.add(Dense(1))

# compile model
model.compile(optimizer='adam',loss='mean_squared_error')

In [19]:
# fit the model
model.fit(predictors,target,epochs=100,validation_split=0.3,verbose=2)

Epoch 1/100
23/23 - 2s - loss: 1657.1703 - val_loss: 1147.9991
Epoch 2/100
23/23 - 0s - loss: 1535.1099 - val_loss: 1027.5255
Epoch 3/100
23/23 - 0s - loss: 1334.2369 - val_loss: 843.2808
Epoch 4/100
23/23 - 0s - loss: 1030.9908 - val_loss: 597.6860
Epoch 5/100
23/23 - 0s - loss: 668.8653 - val_loss: 360.6090
Epoch 6/100
23/23 - 0s - loss: 394.2741 - val_loss: 219.5828
Epoch 7/100
23/23 - 0s - loss: 280.3733 - val_loss: 168.0503
Epoch 8/100
23/23 - 0s - loss: 245.6120 - val_loss: 150.1041
Epoch 9/100
23/23 - 0s - loss: 223.9513 - val_loss: 145.8911
Epoch 10/100
23/23 - 0s - loss: 211.0276 - val_loss: 137.2895
Epoch 11/100
23/23 - 0s - loss: 200.7767 - val_loss: 139.1914
Epoch 12/100
23/23 - 0s - loss: 193.3244 - val_loss: 135.4007
Epoch 13/100
23/23 - 0s - loss: 187.0236 - val_loss: 134.2923
Epoch 14/100
23/23 - 0s - loss: 181.8597 - val_loss: 133.8134
Epoch 15/100
23/23 - 0s - loss: 177.4257 - val_loss: 133.1634
Epoch 16/100
23/23 - 0s - loss: 173.1807 - val_loss: 132.0658
Epoch 17/100
23/23 - 0s - loss: 169.7575 - val_loss: 129.5673
Epoch 18/100
23/23 - 0s - loss: 166.5913 - val_loss: 130.6014
Epoch 19/100
23/23 - 0s - loss: 163.5599 - val_loss: 132.0493
Epoch 20/100
23/23 - 0s - loss: 160.6040 - val_loss: 128.8199
Epoch 21/100
23/23 - 0s - loss: 157.4729 - val_loss: 129.0180
Epoch 22/100
23/23 - 0s - loss: 154.9316 - val_loss: 128.1836
Epoch 23/100
23/23 - 0s - loss: 152.6742 - val_loss: 128.3331
Epoch 24/100
23/23 - 0s - loss: 150.3789 - val_loss: 129.2026
Epoch 25/100
23/23 - 0s - loss: 148.1692 - val_loss: 127.2892
Epoch 26/100
23/23 - 0s - loss: 146.4302 - val_loss: 131.3040
Epoch 27/100
23/23 - 0s - loss: 144.9283 - val_loss: 129.5466
Epoch 28/100
23/23 - 0s - loss: 142.8509 - val_loss: 129.6901
Epoch 29/100
23/23 - 0s - loss: 141.4223 - val_loss: 129.7525
Epoch 30/100
23/23 - 0s - loss: 139.3349 - val_loss: 130.0315
Epoch 31/100
23/23 - 0s - loss: 137.4428 - val_loss: 129.2197
Epoch 32/100
23/23 - 0s - loss: 135.7299 - val_loss: 132.2234
Epoch 33/100
23/23 - 0s - loss: 134.4422 - val_loss: 129.8719
Epoch 34/100
23/23 - 0s - loss: 132.5293 - val_loss: 131.5194
Epoch 35/100
23/23 - 0s - loss: 131.4178 - val_loss: 130.7786
Epoch 36/100
23/23 - 0s - loss: 129.6701 - val_loss: 133.5138
Epoch 37/100
23/23 - 0s - loss: 128.6222 - val_loss: 132.3675
Epoch 38/100
23/23 - 0s - loss: 126.8340 - val_loss: 133.0298
Epoch 39/100
23/23 - 0s - loss: 125.8883 - val_loss: 132.3669
Epoch 40/100
23/23 - 0s - loss: 124.5401 - val_loss: 131.5048
Epoch 41/100
23/23 - 0s - loss: 122.7198 - val_loss: 134.3985
Epoch 42/100
23/23 - 0s - loss: 121.2072 - val_loss: 133.1132
Epoch 43/100
23/23 - 0s - loss: 120.1293 - val_loss: 132.1594
Epoch 44/100
23/23 - 0s - loss: 119.1609 - val_loss: 130.7251
Epoch 45/100
23/23 - 0s - loss: 117.8752 - val_loss: 132.1395
Epoch 46/100
23/23 - 0s - loss: 115.7711 - val_loss: 131.5134
Epoch 47/100
23/23 - 0s - loss: 114.8988 - val_loss: 130.0636
Epoch 48/100
23/23 - 0s - loss: 111.9300 - val_loss: 130.4916
Epoch 49/100
23/23 - 0s - loss: 109.8835 - val_loss: 128.6244
Epoch 50/100
23/23 - 0s - loss: 108.5631 - val_loss: 129.2813
Epoch 51/100
23/23 - 0s - loss: 105.9474 - val_loss: 127.1308
Epoch 52/100
23/23 - 0s - loss: 102.5171 - val_loss: 128.9021
Epoch 53/100
23/23 - 0s - loss: 100.8050 - val_loss: 127.4427
Epoch 54/100
23/23 - 0s - loss: 98.1936 - val_loss: 122.7736
Epoch 55/100
23/23 - 0s - loss: 94.6249 - val_loss: 125.6158
Epoch 56/100
23/23 - 0s - loss: 91.7981 - val_loss: 122.3587
Epoch 57/100
23/23 - 0s - loss: 89.0744 - val_loss: 125.0721
Epoch 58/100
23/23 - 0s - loss: 86.6637 - val_loss: 122.2519
Epoch 59/100
23/23 - 0s - loss: 84.0681 - val_loss: 115.7796
Epoch 60/100
23/23 - 0s - loss: 80.5677 - val_loss: 118.1955
Epoch 61/100
23/23 - 0s - loss: 77.2422 - val_loss: 116.9919
Epoch 62/100
23/23 - 0s - loss: 74.4668 - val_loss: 115.1788
Epoch 63/100
23/23 - 0s - loss: 71.6532 - val_loss: 113.4811
Epoch 64/100
23/23 - 0s - loss: 69.4602 - val_loss: 108.4983
Epoch 65/100
23/23 - 0s - loss: 67.1355 - val_loss: 109.0494
Epoch 66/100
23/23 - 0s - loss: 64.0771 - val_loss: 109.5385
Epoch 67/100
23/23 - 0s - loss: 62.2792 - val_loss: 106.9695
Epoch 68/100
23/23 - 0s - loss: 60.3803 - val_loss: 108.8550
Epoch 69/100
23/23 - 0s - loss: 58.6006 - val_loss: 105.1208
Epoch 70/100
23/23 - 0s - loss: 57.7365 - val_loss: 108.6186
Epoch 71/100
23/23 - 0s - loss: 56.3693 - val_loss: 101.5100
Epoch 72/100
23/23 - 0s - loss: 55.5005 - val_loss: 106.6175
Epoch 73/100
23/23 - 0s - loss: 53.8349 - val_loss: 111.0501
Epoch 74/100
23/23 - 0s - loss: 52.4047 - val_loss: 103.8083
Epoch 75/100
23/23 - 0s - loss: 51.2484 - val_loss: 103.6333
Epoch 76/100
23/23 - 0s - loss: 49.9499 - val_loss: 105.9260
Epoch 77/100
23/23 - 0s - loss: 48.9172 - val_loss: 103.3252
Epoch 78/100
23/23 - 0s - loss: 47.9955 - val_loss: 106.4533
Epoch 79/100
23/23 - 0s - loss: 47.1129 - val_loss: 113.4697
Epoch 80/100
23/23 - 0s - loss: 46.3235 - val_loss: 101.9517
Epoch 81/100
23/23 - 0s - loss: 45.8760 - val_loss: 102.2007
Epoch 82/100
23/23 - 0s - loss: 44.8760 - val_loss: 106.5606
Epoch 83/100
23/23 - 0s - loss: 45.3979 - val_loss: 112.4257
Epoch 84/100
23/23 - 0s - loss: 43.9643 - val_loss: 116.1333
Epoch 85/100
23/23 - 0s - loss: 42.4481 - val_loss: 110.4976
Epoch 86/100
23/23 - 0s - loss: 42.1510 - val_loss: 108.9659
Epoch 87/100
23/23 - 0s - loss: 41.4877 - val_loss: 112.1682
Epoch 88/100
23/23 - 0s - loss: 40.7257 - val_loss: 115.7214
Epoch 89/100
23/23 - 0s - loss: 40.1199 - val_loss: 106.9514
Epoch 90/100
23/23 - 0s - loss: 39.6648 - val_loss: 122.4903
Epoch 91/100
23/23 - 0s - loss: 39.4640 - val_loss: 109.0386
Epoch 92/100
23/23 - 0s - loss: 38.9067 - val_loss: 120.4637
Epoch 93/100
23/23 - 0s - loss: 38.4377 - val_loss: 117.9425
Epoch 94/100
23/23 - 0s - loss: 37.8098 - val_loss: 112.0545
Epoch 95/100
23/23 - 0s - loss: 37.6733 - val_loss: 121.3511
Epoch 96/100
23/23 - 0s - loss: 37.4007 - val_loss: 121.4684
Epoch 97/100
23/23 - 0s - loss: 36.3262 - val_loss: 116.4682
Epoch 98/100
23/23 - 0s - loss: 36.9460 - val_loss: 118.7046
Epoch 99/100
23/23 - 0s - loss: 36.0127 - val_loss: 113.0954
Epoch 100/100
23/23 - 0s - loss: 35.7685 - val_loss: 122.1207